name: Build The Docs

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install deps
      run: npm i
    - name: Ensure the Docs Builds
      run: npm run build
